apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server-deployment
  namespace: spring-microservice-ns
  labels:
    app: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
        - name: auth-server
          image: diman567/auth-server:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8060
          envFrom:
            - configMapRef:
                name: global-config-map
            - configMapRef:
                name: auth-server-config-map
            - secretRef:
                name: infrastructure-mongo-auth-secrets
            - secretRef:
                name: infrastructure-rabbit-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: auth-server-service
  namespace: spring-microservice-ns
spec:
  type: ClusterIP
  selector:
    app: auth-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8070

