apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server-deployment
  namespace: spring-microservice-ns
  labels:
    app: gateway-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-server
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
      containers:
        - name: gateway-server
          image: diman567/gateway-server:0.0.1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: global-config-map
            - configMapRef:
                name: gateway-server-config-map
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-server-service
  namespace: spring-microservice-ns
spec:
  type: ClusterIP
  selector:
    app: gateway-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

